allowBuilds:
  '@clerk/shared': true
  esbuild: true
  msw: false
  sharp: true
  unrs-resolver: true
overrides:
  '@esbuild-kit/esm-loader': 'npm:tsx@^4'
  postcss@<8.5.10: ^8.5.10
  mdast-util-to-markdown: 2.1.2
